# portas "porta do container":"porta da máquina" 

version: '3.1'

services:

  php:
    image: php:7.2-apache
    ports:
      - 9000:80
    working_dir: /var/www/html
    volumes: 
      - ./:/var/www/html
    

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: coloque-sua-senha

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
